name: publish-release

on:
  push:
    tags:
      - '*'

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "tag=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          export DOCKER_IMAGE_NAME=ghcr.io/$GITHUB_ACTOR/kamidata-cli
          docker build \
            --tag ${DOCKER_IMAGE_NAME}:latest \
            --tag ${DOCKER_IMAGE_NAME}:${{steps.get_version.outputs.tag}}
          .
      - name: Push Docker Image
        run: |
          export DOCKER_IMAGE_NAME=ghcr.io/$GITHUB_ACTOR/kamidata-cli
          docker push -a ${DOCKER_IMAGE_NAME}
